### ISSUE TITLE
Saving of the narratives

### ISSUE THREAD

**Issue by brandinalexander** [unicef/etools-partner-reporting-portal#1086]
When a long narrative is pasted into the system, then the user does not see anything happening. The user assumes that all is saved and proceeds to enter other data. However, there narrative is still saving and any data entered after are not saved. This gives the impression that there is some data loss. 

**2 things are needed:**
- [ ] some indication that the saving process is still happening 
- [ ] the saving process must be faster, as it takes a very long time for text that is slightly longer"

----------------
**Trello Ticket**
https://trello.com/c/y8jvRmlc/8-saving-of-the-narratives

**Comment by AttilaTheHen** [comment]
@n1207n @brandinalexander Upon taking a closer look, it looks like there's a discrepancy between the character limits on the frontend and the backend. The frontend forms all say that the character limit is 2000, but as soon as I tried entering a chunk of text around 1900 characters, I get a `PATCH` error in the console telling me that the limit on the backend is 255.

Which limit is correct? It could be that this issue is the underlying problem behind a long narrative not saving, since 255 characters is pretty short.
