### ISSUE TITLE
When locations are removed in PD (pmp) handle that and mark that location and through table as inactive and not use it for future report generation

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#1093]
In PD sync we should detect locations removed and mark them as inactive.

Currently we don't do anything about it. In report generation then only use the active locations to generate the ILD's

**Comment by n1207n** [comment]
For a Cluster indicator side, we currently don't allow deleting any locations. You can only add new locations.

Therefore, it's impossible to mark location goals in any Cluster indicator as inactive at this time. We may want to visit this as a separate new ticket.

**Comment by n1207n** [comment]
This is functional now.

I manually added a new location goal with inactive flag, and regenerated progress reports from scratch. The report only had indicator location data from active locations only.

I also made all location goals inactive and run PD sync task again, my manually-added location did not get activated since it does not exist from PD sync response.
