### ISSUE TITLE
Being able to report on indicator to cluster and UNICEF (should only require frontend work)

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#155]
Mockup: https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016138

The main change is only 1 set of disaggregation checkboxes needs to be shown.

linked to #36 and #37 - please review them and associated questions etc.

**Open Issues**
- Just because a cluster activity indicator has been selected in PD, partner has to adopt the entire cluster activity and all the other indicators as well in the cluster reporting interface?
- Frequency of reporting not matching up with PD/PR and cluster indicator?
- Locations not aligning can be an issue.
- Reports in draft would show up in cluster interface as well.
- Submitted report could get approved by IMO, but denied (in context of progress report) by officer in PMP?
- Lot of edge cases around it: one suggestion is not do a side-by-side reporting interface since it'll add a lot of additional complexity / if-else logic.

**Technical design**

**Comment by kasfaw** [comment]
linked to #36 and #37

**Comment by chachra** [comment]
Can you help on the backend of this @dfryta - basically the submit endpoint needs to take 2 reports, should be doable (against 2 separate reportables).

Think the GET call already exists. Would be great to have it working in IP reporting at least for now. Tx.

**Comment by dfryta** [comment]
@chachra Let's talk about this, because I do not understand logic here. 

1. User go to Cluster, Results and expand one of Indicator Report, for example:
http://prp.tivixlabs.com/app/LV/cluster-reporting/plan/12/results/draft?page_size=10&page=1
2. Here he got all Indictor Location Data (per location).
3. He can edit/submit data.

In mockups I can see two tables (matrices). Questions:
1. What is /where come from second table? At this moment we just use this endpoint: `http://prp.tivixlabs.com/api/indicator/325/indicator-reports/?pks=147946&limit=1`.
2. In case of submit, we just use `/api/indicator/indicator-location-data-entries/` to update one IndicatorLocationData, including disaggregation data. Shouldn't be enough to call this endpoint twice, each of IndicatorLocationData (first and second table)?
