### ISSUE TITLE
PMP Sync: all partners from eTools (PMP)

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#16]
run a job every day to sync parts from /api/partners endpoint in eTools 

**Basic Steps**
1. sync all partners from `/api/partners` wher `hidden=false`
2. search by `vendor_number` and either add new partners or update the info of existing partners
3. update the below fields for each partner

Fields   from /api/partners | Fields in `partners` model
-- | --
vendor_number | vendor_number
name | title
short_name | short_title
partner_type | partner_type
cso_type | cso_type
rating | rating
shared_partner | shared_partner
email | email
phone_number | phone_number
total_ct_cp | total_ct_cp
total_ct_cy | total_ct_cy

**Comment by kasfaw** [comment]
will still need to provide way to add non-UNICEF partners here fyi

**Comment by kasfaw** [comment]
@chachra is this best placed around PMP-PRP integration? There are a few questions I couldn't answer:
* since partners are stored (associated?) separately by workspace in PMP, should PRP do the same or makes more sense to have a global set where we can associate a partner org by workspace, response plan, and cluster? The latter seems to make more sense IMO; would require some mods to the PRP partner model too (ie FK to workspace and response plan)
* Is the idea to run a sync nightly on all partner records form PMP?
* should we sync the staff member model as well? Even though ID portal will be handling user management, there is legacy data that would require migration. Other way to handle this would be to simply add any unique email address from the `officer_programme_documents` and `unicef_focal_programme_documents` fields of the PDs we sync

**other considerations we should make**
* we need a way for an IMO to add a new partner in cluster reporting. it will not always be the case that a contributing partner is also an active partner with unicef.

**Comment by kasfaw** [comment]
~Note from Friday chat with @chachra ~
* we will associate partners to clusters and PDs. this means we keep partners agnostic to a workspace 
* will work with @robertavram and team on how sync will work (above description focused on general process)
* no need to sync staff members model. PD sync will handle association of necessary staff members (story here: #17) 
* will keep cluster Partner add process in django admin and keep it for post v1
