### ISSUE TITLE
Misc. API changes needed

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#201]
Some of these might already be in place, please comment, otherwise do in a feature branch asap.

Make sure Indicator list API (same used in IP reporting) supports filtering by "reportable id" (anything this indicator has a generic relation with). Eg. a cluster objective with ID XYZ can see indicators associated with it easily. https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232533791

Make sure cluster activity API endpoint can be filtered by "cluster objective ID". Since each cluster activity belongs to one specific CO/Cluster objective this should be easy/doable: https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232533790

Be able to get a list of partners with appropriate fields in the API GET request for a cluster activity. Basically these are partners who are doing activities whose parent is this cluster activity. Eg. endpoint will be /api/..../cluster-activity/34/partners/ -> it'll return partners that are doing activities whose parent/associated cluster activity is ID 34. UI that needs it is here: https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232533941

Be able to filter the partner activity list by partner project id (since each partner activity belongs to one partner project): https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/233065469

The newly added indicator-reports API endpoint should support "limit" so we can show latest 5-10 on the dashboard like here: https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232073629

**Comment by chachra** [comment]
@lkolacz please review and comment on technical design / issues / any questions you have on this task. Thanks.

**Comment by chachra** [comment]
@n1207n @lkolacz additionally can you both please do a diff on any minor API tweaks needed we haven't thought of and add here? Thanks.

**Comment by lkolacz** [comment]
Make sure Indicator list API (same used in IP reporting) supports filtering by "reportable id" (anything this indicator has a generic relation with). Eg. a cluster objective with ID XYZ can see indicators associated with it easily. https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232533791

_Indicator list API (endpoint 'indictor-list-create-api') contain filter by reportable id (example `http://localhost:8080/api/indicator/?id=3`)
the same filter is for `ClusterIndicatorsListAPIView` called `reportable id` .._ 

Make sure cluster activity API endpoint can be filtered by "cluster objective ID". Since each cluster activity belongs to one specific CO/Cluster objective this should be easy/doable: https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232533790

_Didin't exists -> added !!! .. url example with filter `http://localhost:8080/api/cluster/cluster-activity-list/?cluster_objective_id=2`_

Be able to get a list of partners with appropriate fields in the API GET request for a cluster activity. Basically these are partners who are doing activities whose parent is this cluster activity. Eg. endpoint will be /api/..../cluster-activity/34/partners/ -> it'll return partners that are doing activities whose parent/associated cluster activity is ID 34. UI that needs it is here: https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232533941

_new endpoint url example `http://localhost:8080/api/partner/cluster-activity/39/partners/` can be filtered by extra query param like `?partner=39`_

**Comment by lkolacz** [comment]
all changes are done in `feature-API-changes-needed-#201` branch
