### ISSUE TITLE
Add activities, partners (some screens) tabs to cluster objective, cluster activity and partner project detail screens in cluster reporting

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#211]
Mockups: PRP cluster reporting

Nav: Everything under response parameters, my planned action.

**Technical notes**
#201 should have put all necessary API's needed in place by now.

**Comment by ErinOC** [comment]
@n1207n:
The /partner/cluster-activity/39/partners/ needs to also return:
- A contact person ('focal point' in the mockup)
- A cluster (or clusters) name
(Not urgent; do Rafal's API first)

**Comment by ErinOC** [comment]
@n1207n:
The partner-activity-list needs to return the also project activity title: https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232532636

Currently it is returning: [{id: 37, cluster: "cluster_42", status: "Ong", project: 77, cluster_activity: 44}]

**Comment by n1207n** [comment]
@chachra, 

https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232533941

Above mockup is a contributing partner list tab page for cluster activity. the field `focal_point` only exists in ProgrammeDocument model, but in the cluster world I don't think it's possible to access PD, since there is no PD right?

Should we omit the field or make data model change??

**Comment by n1207n** [comment]
@ErinOC,

I have added clusters field to cluster-activity-partners API (e.g /partner/cluster-activity/39/partners/) There is no way for cluster portal to see focal_point field as that is PD exclusive field. I'll lean on Sumit's decision on this.

I have used `partner` field as a serialized object to include title on partner-activity-list API.

Let me know if I missed anything or need more API data.

Thanks.
