### ISSUE TITLE
Minor fixes relating to #211

### ISSUE THREAD

**Issue by ErinOC** [unicef/etools-partner-reporting-portal#245]
#220 builds upon #211 and it is getting complicated, so I want to avoid any branching issues and get #211 merged.  There are some known issues in #211 that need to be fixed but are isolated enough that they shouldn't hold up merge. Listing them here.

**Clusters —> Objective —> Activities:** 
Link to the activity does not work (removed for now)
Filter: Activity should be a dropdown.*  Move CLEAR button to the same line.

**Clusters —> Activities —> Contributing Partners:** 
Partner column needs better formatting when there are multiple projects, as well as links
Need link for "SEE ACTIVITY"  https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232533941
Need partner filter*

**Partners —> Projects (and My Planned Actions projects)**
Need project activity title and link in the table.
Needs filters*  https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232532636

* Not sure if we need to include these. There was some question about the usefulness of filters in an already limited/pre-filtered list.

**Comment by rkrupinski** [comment]
@kidus

> Link to the activity does not work (removed for now)

Works for me.

> Filter: Activity should be a dropdown.* Move CLEAR button to the same line.

I'm not sure how this would work. We're looking at a paginated list of activities. yet we'd like to filter it by title to narrow the list below to one item? Doesn't a text field do the job better since it allows entering a chunk of title and narrowing the list to all matching activities?

**Comment by kasfaw** [comment]
@rkrupinski agreed. having a search field makes more sense

**Comment by kasfaw** [comment]
@rkrupinski SEE ACTIVITY should link to the partner's activity overview page (https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/232533045)

**Comment by rkrupinski** [comment]
@kidus @n1207n 

Given the contributing partner record (of the format below), how do I compute partner's activity page url? Unless all partners contribute to the same activity which makes this trivial.

```js
{
  "id": 13,
  "title": "Åland Islands 2016 Humanitarian Response Plan - WASH Cluster Partner",
  "email": null,
  "phone_number": null,
  "partner_projects": [
    {
      "id": 12,
      "title": "Åland Islands 2016 Humanitarian Response Plan - WASH Cluster Partner Partner Project"
    },
    {
      "id": 11,
      "title": "Åland Islands 2016 Humanitarian Response Plan - WASH Cluster Partner Partner Project"
    }
  ],
  "street_address": null,
  "city": null,
  "postal_code": null,
  "links": [
    "additional_information 11",
    "additional_information 10"
  ],
  "clusters": [
    {
      "id": 44,
      "title": "WASH"
    }
  ]
}
```

**Comment by rkrupinski** [comment]
@kasfaw @n1207n 

Given the project record (of the format below), how do I calculate the activity url?

```js
{
  "id": "12",
  "title": "Åland Islands 2016 Humanitarian Response Plan - WASH Cluster Partner Partner Project",
  "start_date": "2017-01-01",
  "end_date": "2017-08-28",
  "status": "Ong",
  "description": "description 11",
  "additional_information": "additional_information 11",
  "total_budget": "26190.10",
  "funding_source": "funding_source 11",
  "clusters": [
    {
      "id": 44,
      "title": "WASH"
    }
  ],
  "locations": [
    {
      "id": "301",
      "title": "location_281"
    }
  ],
  "partner": "13",
  "part_response_plan": "Åland Islands 2016 Humanitarian Response Plan"
}
```

**Comment by rkrupinski** [comment]
@kasfaw 

According to mockup, we want to filter projects (both partner & my planned action) by cluster activity. Don't these cross-depend on each other?

- should the activity filter only show activities for selected cluster?
- if so, can we even do that since the API for fetching activities only accepts one cluster id and the cluster filter (according to mockups) is a multi-select?

cc @n1207n

**Comment by kasfaw** [comment]
@rkrupinski 

** regarding the API response**
* the list of contributing partners you would see here have the same parent activity they contribute to, but their activity id would be different. the json response doesnt seem to show the activity id of the partner which i think makes sense to have. Perhaps we need to add this?
* a partner activity is a subset of a partner project so you can always expect a partner activity to be associated to a partner project

**According to mockup, we want to filter projects (both partner & my planned action) by cluster activity. Don't these cross-depend on each other?**
* the cluster activity filter would show all activities that have the filtered cluster activity as its parent. This filter seems redundant in my planned action and i would remove it. It makes sense to show it in the Response Param > Partners list though.

**should the activity filter only show activities for selected cluster?**
* yes
**if so, can we even do that since the API for fetching activities only accepts one cluster id and the cluster filter (according to mockups) is a multi-select?**
* There is the chance that it is filtered by All clusters, in which case the cluster filter would have more utility.

**Comment by kasfaw** [comment]
@dfryta can you please please add the partner_activity_id as a field to this endpoint: /partner/cluster-activity/<cluster-activity-id>/partners

**Comment by dfryta** [comment]
Yes, will do.

**Comment by dfryta** [comment]
@kasfaw One question here - partners have multiple partner_activity(ies). So I can return a list of them, not only one. Is this OK?

**Comment by kasfaw** [comment]
@dfryta sounds good.

**Comment by dfryta** [comment]
Done.
