### ISSUE TITLE
Determining Due vs Overdue report_status for an indicator report

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-partner-reporting-portal#272]
**requirement for both IP and cluster reporting**

- [x] Unless due_date is explicitly indicated for a report, due_date == end_date + 15 days

- [x] IF due_date >= TODAY >= end_date THEN status == Due ; IF  due_date < TODAY THEN status == Overdue

**Comment by dfryta** [comment]
Sounds good, but I have couple questions/thoughts here. Let me focus on IP since I have no knowledge about Cluster yet.

Programme Document report status should be overdue when one of assigned indicator report is overdue. Otherwise Programme Document report status is due. Is that correct?

Moving forward, indicator report  report_status is due when due_date is greater then TODAY. If due_date is lesser then TODAY and submission_date is empty - it's overdue. If there is submission date provided, report_status is Submitted, Sent back or Accepted. I wonder here if Sent back we should treat like overdue?

We should probably also setup a cronjob that will update Indicator Reports daily basis (compare TODAY with due_date) plus create a post_save signal that will update Programme Document / Cluster report_status after every report_status change in indicator instance.

Currently we hit to database every time we get Cluster or ProgrammeDocument status, calculating value from assigned Indicator Reports.

Let me know your thoughts. Thanks!

**Comment by kasfaw** [comment]
@dfryta i have updated the requirements. Hope this clarifies things

**Comment by dfryta** [comment]
Thanks @kasfaw. One more question - how we treat entries with filled submission_date? We should skip them from logic? How about Sent Back?

**Comment by kasfaw** [comment]
Correct @dfryta If submission date is entered, that become the due date

**Comment by dfryta** [comment]
Done for Indicator reports. To run we have to add into cron:
`python manage.py runcrons`

**Comment by kasfaw** [comment]
@dfryta we need to run this on ProgressReports too
