### ISSUE TITLE
"reports" tab under PD

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#29]
https://projects.invisionapp.com/share/RDBE0T04F#/screens/230016132

Shows all due and past submitted reports for this PD.

See #23 - except in this interface we just want filtering by status.

url can be /pd/$id/reports/

**Comment by chachra** [comment]
Comes after #28

**Comment by lkolacz** [comment]
issue #28 is done from backend perspective and it's on PR 
common branch for this issue is `feature-Single-PD-reports-list#29`

**Comment by adamtlord** [comment]
@rkrupinski Could you take a look at this please? I can't figure out why the default page and page_size queryParams are not getting appended to the url they way they do with pd-list. The only thing I've been able to figure out so far is that `iron-location`'s {{ query }} and `iron-query-param`'s {{ params-string }} seem to be in conflict with each other

**Comment by rkrupinski** [comment]
@adamtlord Please comment on an actual changeset/pull request next time :)

**Comment by rkrupinski** [comment]
@adamtlord Done. `git pull`.

A few insights:

* How about unifying report statuses in order to merge https://github.com/unicef/etools-partner-reporting-portal/blob/feature-Single-PD-reports-list%2329/polymer/src/elements/progress-report-status.html and https://github.com/unicef/etools-partner-reporting-portal/blob/feature-Single-PD-reports-list%2329/polymer/src/elements/report-status.html ? They share 95% of the code. How about going even further and making it use https://github.com/unicef/etools-partner-reporting-portal/blob/feature-Indicator-data-tab-submitted-report-viewing-%2374/polymer/src/elements/status-badge.html (not yet in `develop`) internally?
* Not sure whether location change being a trigger for data fetching is the best idea (as it happens in another place of the app): https://github.com/unicef/etools-partner-reporting-portal/blob/feature-Single-PD-reports-list%2329/polymer/src/pages/app/ip-reporting/pd/pd-details.html#L164
* Here https://github.com/unicef/etools-partner-reporting-portal/blob/feature-Single-PD-reports-list%2329/polymer/src/pages/app/ip-reporting/pd/pd-details.html#L152-L158 - instead of observing a property whose type is `Object`, create a complex observer (`observers: [ '_foo(routeData.dashTab)', ]`) to only watch for a property change. Sometimes a property can change while the reference to the parent object stays intact and the observer won't be able to pick up this change.

**Comment by adamtlord** [comment]
@rkrupinski I totally agree on location change not being the best trigger for fetching pd reports, but I need the location ID to construct the endpoint url for pd details. So I thought it would be best to listen for location to get set in the state. Otherwise, if I try to fetch data on `attached()`, for example, I get a 404 because with the location ID undefined, the endpoint url is `/api/unicef//programme-document/details/1`.

**Comment by rkrupinski** [comment]
@adamtlord I failed to make my point 😄 I didn't mean not relying on location at all; I meant a proper dependency hierarchy. What depends (and has to depend on, for obvious reasons) on location, is `programmeDocumentDetailsUrl`. The only thing data fetching logic should depend on is this url.

I just pushed a "fix":
https://github.com/unicef/etools-partner-reporting-portal/commit/1f41227e265b0bcb4ac3764b44055abd3285e907#diff-6037d2ab635f990742449b469881d86dR133
