### ISSUE TITLE
Model Changes

### ISSUE THREAD

**Issue by kasfaw** [unicef/etools-partner-reporting-portal#298]
Reference to data model here: https://www.lucidchart.com/documents/edit/213804d2-b329-470d-a540-a247bb72af60/0

- [x] Cluster: change `title` to dropdown with following options - CCCM, Early Recovery, Education, Emergency Telecommunications, Food Security, Health, Logistics, Nutrition, Protection, Shelter, WASH; put a unique constraint to response plan and type

- [ ] Cluster: change `response_plan` and `user` to multiselects

- [ ] Cluster: add multiselect FK to `partners`

- [ ] Response Plan: add multiselect FK to `cluster` and add attachment field

- [x] Programme Document: `organization_name` should be FK to `partners`

- [x] Progress Report: add `due_date` `submission_date` and a `submitted_by` FK to `users`

- [x] Reportable: change `due_date` to `end_date`

- [x] LLO: change `indicator` to a multiselect

- [x] Cluster Objective: add FK to `locations`

- [x] Cluster Activity: add FK to `locations`

- [x] Partner Project: add FK to `locations`

- [x] Partner Activity: add FK to `locations`

**expose relationship between Disaggregation and Reportable models in Django Admin**

**Comment by chachra** [comment]
Partner project already had locations M2M.

"Cluster: change response_plan and user to multiselects" is not needed... since each "cluster object" in the db is meant to be for a response plan.

"Cluster: add multiselect FK to partners" is not needed as well we think, hence. so a partner will belong to a cluster that exists to belong to a response plan and hence forth. So there is no global thing to say "this partner belongs to 'all WASH' clusters in all response plans". Thinking this is not a blocker, in fact its a good granular control.... now where this is managed is a good question, think django admin or via a invite flow via IMO.

QUESTION: Is a user an IMO for a cluster, a response plan or entire workspace (my preference for last one....).

"Response Plan: add multiselect FK to cluster" not doing since cluster points to RP already... so effect is same.

"Programme Document: organization_name should be FK to partners" -> added fk to one partner from PD.

"Progress Report: add due_date submission_date and a submitted_by FK to users" - Done... but added sent_back_date, sent_back_feedback. Cool? 

+    due_date = models.DateField(verbose_name='Due Date')
+    submission_date = models.DateField(verbose_name='Submission Date',
+                                       blank=True, null=True)
+    submitted_by = models.ForeignKey('account.User',
+                                     blank=True, null=True)
+
+    sent_back_date = models.DateField(verbose_name='Sent Back Date',
+                                      blank=True, null=True)
+    sent_back_feedback = models.TextField(blank=True, null=True)


"Reportable: change due_date to end_date" -> there is no due date in code... it is end date already?

"LLO: change indicator to a multiselect" --> So it was a wording issue, changed to. The LLO already can have many reportables associated with it (just like activities, objectives etc.) via the GenericRelation.  Changed to cp_output = models.ForeignKey(CountryProgrammeOutput, related_name="ll_outputs"). If you go to reporable (the right one... since not all are related to a LLO) you can see https://www.evernote.com/l/AAWvq0HPhMNGRZX27372hebLTXGSTYm6w_o so relation is good to go.

**Comment by chachra** [comment]
@kasfaw @n1207n  change partner.country_code to be a FK to country as well?

**Comment by kasfaw** [comment]
@chachra we would want a partner to FK to workspaces no?

**Comment by kasfaw** [comment]
* Partner project already had locations M2M.
  * **got it**

* "Cluster: change response_plan and user to multiselects" is not needed... since each "cluster object" in the db is meant to be for a response plan.
  * ** @chachra there should be the possibility to select multiple IMOs to a cluster in a response plan. Shouldn't we allow many `user` to a `cluster`? **

* "Cluster: add multiselect FK to partners" is not needed as well we think, hence. so a partner will belong to a cluster that exists to belong to a response plan and hence forth. So there is no global thing to say "this partner belongs to 'all WASH' clusters in all response plans". Thinking this is not a blocker, in fact its a good granular control.... now where this is managed is a good question, think django admin or via a invite flow via IMO.
  * **agreed. i have made update to the data model design to reflect 1-to-many relationship between `cluster` and `partners`**

* QUESTION: Is a user an IMO for a cluster, a response plan or entire workspace (my preference for last one....).
  * ** @chachra a user is an IMO for the entire workspace (best fits our ID portal logic too), BUT we should have a way to indicate the cluster the `user` is an IMO for. This will enable us to default the cluster dropdown to the one the IMO belongs to by default **

* "Response Plan: add multiselect FK to cluster" not doing since cluster points to RP already... so effect is same.
  * **got it**

* "Programme Document: organization_name should be FK to partners" -> added fk to one partner from PD.
  * **got it**

* "Progress Report: add due_date submission_date and a submitted_by FK to users" - Done... but added sent_back_date, sent_back_feedback. Cool?
  * **cool!**

* "Reportable: change due_date to end_date" -> there is no due date in code... it is end date already?
  * ** @chachra the issue seems to be with  `end_date = models.DateField(verbose_name='Due Date',)` in django_api/django_api/apps/unicef/models.py ;  Shouldn't we change to `verbose_name='End Date'`?**

* "LLO: change indicator to a multiselect" --> So it was a wording issue, changed to. The LLO already can have many reportables associated with it (just like activities, objectives etc.) via the GenericRelation. Changed to cp_output = models.ForeignKey(CountryProgrammeOutput, related_name="ll_outputs"). If you go to reporable (the right one... since not all are related to a LLO) you can see https://www.evernote.com/l/AAWvq0HPhMNGRZX27372hebLTXGSTYm6w_o so relation is good to go.
  * **got it. something for @dfryta to keep in mind in IP reporting is that the `object_id` in `reportable` is the `id` of the `llo`**

**Comment by chachra** [comment]
@kasfaw @dfryta "object_id in reportable is the id of ANYTHING reportables are attached to". So can be llo, can be partner activity etc. as well. this is the orange lines in the data model.

"Shouldn't we change to verbose_name='End Date'" - minor fix... made.

"indicate the cluster the user is an IMO for" - I think you might mean "cluster type" not the actual cluster in db? Since workspace will have many response plans and each will have many clusters, so tying user to the cluster isn't perfect. Think you mean "type"?

"@chachra there should be the possibility to select multiple IMOs to a cluster in a response plan. Shouldn't we allow many user to a cluster?" - not sure I follow... this will be handled via groups/role of user?

"@chachra partner should FK to multiple workspaces no? don't so the value of FK to country_code since their association would lie on what business area, cluster, and/or response plan they have access to. the lowest common denominator for that would be a workspace" - this country_code is already in data model, my q was to make it a fk... I think this is a "fyi" thing... this partner is from X country I think. Comes from PMP as well. Access stuff, per data model partner is associated with cluster as of now, which determines then which workspaces they get access to I guess... not 100% sure how we should interpret it, meaning this partner can only submit reports or create projects for their set of clusters only?... hmm.

**Comment by kasfaw** [comment]
@chachra on cluster-IMO relationship... we would want to make sure that my IMO privledges are contained within the cluster TYPE i belong to. so as the Protection IMO, I should not be able to modify cluster activities of the Nutrition cluster.

@chachra on partner-country... definitely should allow the partner to create projects/activities and submit reports to any cluster in a workspace they have access too.

**Comment by dfryta** [comment]
Added all missing location FK to PartnerActivity, ClusterActivity, ClusterObject. Fixed small issues with some API endpoints, fixed fixtures.
