### ISSUE TITLE
Notification email if calculation method changed for PD with a previously submitted+accepted progress report

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#462]
Alert if partner changes the calculation method in PRP for indicators if any report for that PD has already accepted by UNICEF. Email should contain a link to the calculation method tab in question for the pd which the user can click on. 

Please put a base email template in place if one doesn't already exist that all such emails will use. 

------------------------

Email to: Focal Point(s) associated with the PD
Subject Line: Calculation Method for indicators in PD $name$ have changed
Dear <UNICEF Focal Point Name>,
This is to inform you that the Calculation Method for indicators in PD $name$ have changed.
-$Partner Name$

**Comment by n1207n** [comment]
Putting this on hold until we get confirmation from UNICEF on how this feature should trigger Email on submitted ProgressReport <-> IndicatorBlueprint.

Because ProgressReport does not have a direct link to IndicatorBlueprint, it's not possible to specifically target one ProgressReport from Indicator's calculation method change. All we can do is we can query multiple ProgressReport instances for given Indicator that has ProgrammeDocument link, because associated ProgressReport instances must share the same ProgrammeDocument.
