### ISSUE TITLE
Add concept of report #, type and "final" to progress report in ip reportng

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#463]
On Progress Report List Page, add column called “Report number”, where the report number is generated automatically. The last quarterly progress report (QPR) on the list should be called “final” QPR. The numbering of the reports will depend on the report type, e.g. Special reports would be SR1, Humanitarian will be HR1. The numbers will be generated at the time when the report is generated.

Nice to have: Support sort by Report #

<img width="852" alt="screen shot 2018-02-09 at 5 44 40 pm" src="https://user-images.githubusercontent.com/31295242/36057271-f3600d78-0dc0-11e8-9c5a-60e7285836fc.png">

**Technical notes**
Add report type (QPR (default), HR, SR) to Progress Report model. Also add a "final" boolean (default False), and report # (integer). Also add a unique together for unique for pd + reporttype + #

Update API's to export a nice report # (QPR1, HR2 etc.) in the Progress report list endpoint and progress report detail endpoint as well

Please update fake data, should be quick, to generate reports of type HR or QPR randomly (can ignore SR for now) and final one marked as final.

**Comment by n1207n** [comment]
@marcindo, the backend support for this ticket is complete in `feature-progress-report-field-changes-463` branch. You can implement the Polymer changes in this branch or create a new branch from this branch. It's up to you.

When you get my changes in your environment, you need to destroy and re-create docker environment due to DB unique constraint migration. You can run `fab down` when docker-compose is not running. Once it's up and running, run `fab fixtures:2` to populate new fake dataset. At that point, you're good to go.

Let me know if you need help.

**Comment by n1207n** [comment]
I'll be merging this branch into develop shortly today since #456 needs this branch to be merged for actual ProgressReport model changes according to @maciej-jaworski
