### ISSUE TITLE
Allow IMO to create/edit partner projects+activities.

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#466]
If a user is an IMO for say cluster A & B in Response plan Z then they should be allowed to add/edit projects (and their indicators) and activities (and their indicators) for partners that are associated with clusters X or Y.

The IMO cannot do that for partners that are in cluster C though. Or even for partners in response plan Y.

The "My Planned Action" navigation and all associated sub-navigations is still hidden from the IMO and only partner facing. Hence this add/edit capability for partner projects and partner activities will be exposed under the "response parameters > partners" section.

"response parameters > partners > projects" IMO will see a "add project" button.

"response parameters > partners > partner activities" they will see a "add activity" button.

As already, the IMO can submit data and reports for any indicator report associated with their cluster already.

**Technical notes**

Project/partner activity create API endpoints need to allow a "partner_id" to be posted as well, and will associated that new activity or project with that partner. Doing all necessary data validations of course.

Backend should validate everything, including that this user is an IMO and only for those requests an additional "partner_id" (for creation only) will be expected. For edit, validate the fact that this IMO user is an IMO for a cluster this partner project/activities partner belongs to.

**Frontend changes**
- If this is an IMO user then show a "add project" and "add activity" button under /app/EG/cluster-reporting/plan/43/response-parameters/partners/projects and /app/EG/cluster-reporting/plan/43/response-parameters/partners/activities routes under response parameters > partners

- clicking those buttons should give the exact same modal as a partner would get except now with a "dropdown" to select one partner.

![cluster_reporting___prp](https://user-images.githubusercontent.com/73096/36515149-d2fb23fe-172c-11e8-820b-5761ea48454f.png)

Same for partner activity add modal as well. Would post to different url now thats it, would be eg.
```
# PartnerProject create (POST)
r'^(?P<response_plan_id>\d+)/partner-project-list/partner/(?P<partner_id>\d+)/$

# PartnerProject update (PUT)
r'^partner-project-details/partner/(?P<partner_id>\d+)/(?P<pk>\d+)/$'

# PartnerActivity create (POST)
r'^(?P<response_plan_id>\d+)/create-partner-activity/(?P<create_mode>\w+)$'

# PartnerActivity update (PUT)
r'^(?P<response_plan_id>\d+)/partner-activity/(?P<pk>\d+)/$'
```

- If IMO user then in the project details and partner activity details views there would be a "edit project" and "edit activity" button. Routes for those: /app/EG/cluster-reporting/plan/43/response-parameters/partners/project/77/overview and /app/EG/cluster-reporting/plan/43/response-parameters/partners/activity/1732/overview

- the modals that open for these are exactly the same as would happen for partner under "my planned action".

**Comment by sethgold8** [comment]
Django object-level permissions is ticket #471

**Comment by marcindo** [comment]
@chachra Editing partner associated with the project is fine?

**Comment by marcindo** [comment]
@n1207n in http://localhost:8080/api/partner/partner-project-details/:id/ partner field needs to be dict {id, title}  id not directly the title.

**Comment by marcindo** [comment]
@n1207n also api/partner/3/partner-project-list/partner/:id/ endpoint needs to support patch method

**Comment by n1207n** [comment]
@marcindo, I think editing partner on project/activity is not allowed, as it conflicts with partner's foreignkey links to project/activity on destination. IMO is simply editing the existing info on behalf of the partner. Backend will have validation on partner_id for editing.

After few considerations, I'm updating the API urlpatterns for IMO as it follows:
```
# PartnerProject create (POST)
r'^(?P<response_plan_id>\d+)/partner-project-list/partner/(?P<partner_id>\d+)/$

# PartnerProject update (PUT)
r'^partner-project-details/partner/(?P<partner_id>\d+)/(?P<pk>\d+)/$'

# PartnerActivity create (POST)
r'^(?P<response_plan_id>\d+)/create-partner-activity/(?P<create_mode>\w+)$'

# PartnerActivity update (PUT)
r'^(?P<response_plan_id>\d+)/partner-activity/(?P<pk>\d+)/$'
```

For PartnerProject, the API serializer field for `partner` is actually CharField mainly reserved for List API. Associating partner to newly created PartnerProject is done via backend user object's partner foreignkey, therefore sending partner id as in `partner` in serializer won't do anything. Now for IMO, we need to access `partner_id` from urlpattern, not from IMO user's partner foreignkey link. That's the reason for having `partner_id` in url for PartnerProject.

For PartnerActivity on the other hand, `partner` field in serializer is used for associating partner to PartnerActivity. Therefore, creating PartnerActivity as IMO is identical as Partner user.

I need to make some changes due to above proposal. I'll let you know if both creating/editing is working for above urls.

**Comment by marcindo** [comment]
@n1207n I still need to get the partner_id somehow from  api/partner/partner-project-details/:id/ endpoint to be able to edit

**Comment by n1207n** [comment]
IMO user can only create PartnerProject/PartnerActivity on partner, if IMO user has that partner in his/her clusters. That's the validation error you're seeing there. For Authorized Officer, it only has one partner as you said.

The thing is that partner has clusters as M2M and user has clusters as M2M as well. These 2 M2M fields are mutually exclusive. It may be possible that partner has all clusters in its M2M and user does not have all clusters. I have to think this may be fake data inconsistency which I'm trying to fix on separate branch.

Feel free to try updating partner link in admin_ao user in Django admin so that both admin_ao and admin_imo has same partner. In the meantime, I'll dig some more afterwards.

**Comment by n1207n** [comment]
@marcindo,

The update API for PartnerProject as IMO is `http://localhost:8080/api/partner/partner-project-details/partner/9/43/` where `9` is partner_id and `43` is project_id.

If you're on PartnerProject details page, shouldn't Polymer have access to both ids?

**Comment by marcindo** [comment]
@n1207n so far in both projects list and project details endpoints only title of partner is returned so I might be wrong but I don't see where I could get partner_id

**Comment by n1207n** [comment]
I think currently PartnerProject list and detail API returns id field in their responses. What's the API endpoint you're using from your end?

```
GET http://localhost:8080/api/partner/3/partner-project-list/?page_size=10&page=1&cluster_id=
```

![screen shot 2018-02-23 at 11 38 16 am](https://user-images.githubusercontent.com/3138217/36613358-185eef90-188e-11e8-948f-6694886cdc52.png)

```
GET http://localhost:8080/api/partner/partner-project-details/47/
```

![screen shot 2018-02-23 at 11 39 32 am](https://user-images.githubusercontent.com/3138217/36613400-3f616258-188e-11e8-9638-8b7833e795af.png)

**Comment by marcindo** [comment]
id, yes but not partner_id

**Comment by n1207n** [comment]
I assumed Polymer redux would have access to current partner they're in, but that's for partner user I guess. I can quickly add `partner_id` field to both API endpoints. I'll ping you when it's done. ;)

**Comment by marcindo** [comment]
@chachra @n1207n 
- When I add project as partner (admin_ao) the choice of clusters is filtered by clusters to which partner user is added, there is even frontend component for this very purpose. But when adding partner activities, there is no filtering in place, and I can freely choose any cluster in the workspace. However backend is blocking admin_imo from doing the same, and here I need to pick correct partner_id and matching cluster. I could use the same filtering component, but it would also limit admin_ao from picking any cluster, and I wouldn't like to implement the same logic again but apply it only for one user.

- as a follow up to this issue, it seems I can edit any partner activity as IMO, obviously I'd rather like to not display edit button on activities that don't 'belong' to the user.  But for doing that I'd also need enhanced api/partner/:partner_id/partner-activity/:id/ endpoint to return id of activity cluster not just name `cluster: "WASH"`

**Comment by n1207n** [comment]
@marcindo,

Thanks for your insight on frontend perspective. Here is what I know about partners <-> clusters relationship, so that you may get a clearer understanding to resolve this issue together.

You are correct that partner has many Clusters and we have API and Polymer component to interact this. Currently, PartnerActivity API serializers for creation/update does not do cluster check on partner. Therefore, it is possible for now to add PartnerActivity for any Cluster in a Workspace, however this is wrong behavior. It is illegal to have PartnerActivity outside of its Partner's Clusters under one Workspace.

When we add PartnerActivity, it should do validation where partner belongs to given cluster or not. Currently, PartnerActivity for IMO is doing this validation already and I assumed same validation has taken in place for Partner AO. However based on what you described, that isn't the case.

I will enforce PartnerActivity API for Partner AO to check if partner and cluster belongs to each other.

For your second issue, you are correct that IMO can create/edit any PartnerActivity and PartnerProject objects as long as they belong to its IMO clusters. I can push API change to accommodate both cluster ID and name.

**Comment by sethgold8** [comment]
#works - Seth
