### ISSUE TITLE
Fake data generation

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#50]
Be able to generate fake data on development for the application to be usable / browsable etc. and for testing

**Comment by n1207n** [comment]
UNICEF etools is already using factory-boy for their test factories.

https://factoryboy.readthedocs.io/en/latest/

https://github.com/unicef/etools/search?utf8=%E2%9C%93&q=factory&type=

We should use this factory library as a mean to generate random fake data. We also need some sort of fixture or Python function that generates a bunch of fake data at runtime.

**Comment by lkolacz** [comment]
@n1207n we we want make it more complex???
We can create fixtures .. define `FIXTURE_DIRS` and path...
You can read more at https://docs.djangoproject.com/en/1.11/topics/testing/tools/#fixture-loading

**Comment by n1207n** [comment]
@lkolacz,

There are many reasons for choosing factory-boy to our data generation path.

As you may know that Django fixture data is used for both initial data and test data. Because of the initial data attributes, the fixture data should only create any model data that are not user-generated, such as User, Group, Site, and so on. Your fixture data seems to introduce a whole set of user contents: Cluster, Partner, Intervention, and Partner User object. These contents may not be applicable when we start using system at UNICEF.

Secondly, factory-boy has a higher degree of maintainability. Fixture data is easy and fast to product at the moment, so is high-error prone from database migrations. We are going to make a lot of changes to database tables from now until MVP state. The fact that we create model data declaratively, makes a huge investment for now to aim the future.

Thirdly as I mentioned, UNICEF etools team has been already using factory-boy for their extensive test suite. This nature already gives factory-boy a huge practical reliability. Moreover, UNICEF team members can easily adopt our testing practices if the time comes to deliver technical values.

I would not call using factory-boy unnecessarily complicating the project. It is a necessary and a great project seed to bootstrap. Runtime-test data generation has proven a lot of values besides above reasons.

I'll put some factory-boy codes and reuse your fabric command at this branch. After that, I'll try to merge this branch in so that other branch will benefit from.

**Comment by chachra** [comment]
Document the 2 step process in the README for development: be able to get a fresh db (no data) and in one command be able to get good amount of mock data into the db.
