### ISSUE TITLE
Handle 400 error messages / strings etc. in modals/forms in general

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#511]
Would be good to put a pattern in place. This is an example.

I am not expecting "per field mapping". An error message that simply bullet point li-list wise puts these messages so user knows what went wrong. Right now we don't show any feedback to user.

As an example:

![cluster_reporting___prp](https://user-images.githubusercontent.com/73096/36765799-d95fd9fa-1be7-11e8-853e-0d9f532d0cfb.png)

- [ ] Get proper endpoint for locations and show error message if user selects two different levels @rkrupinski

**Comment by marcindo** [comment]
I've added error box on top of this add indicator modal (try to set baseline larger than target to see it) which looks similar to this mock
![Screen Shot 2018-02-28 at 14.51.15.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5981b9b1d1a31c001f205633/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216456fb6b7191a379eb0c2e50415e4bbe5d4a1f06a3a3dc78e2a436628f5458bbd96e0a74c53b18ffb9871fbf08b8258c4982b4ba9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ec951fe49e64a51a7163566f43b.png)
on branch `511-generic-error-messages`
This could be reused in other places, but there are some catches: 
- backend seems to always return one error at a time (first found I guess) instead of a whole list
- sometimes errors are returned as field-errors just under err.data which is parsed to object, sometimes  as simple list under res.data.errors, and sometimes as just 500 error for missing field where there is no err.data. This needs to be included so we can always translate errors to list, or maybe backend should be more consistent with error messages?

**Comment by maciej-jaworski** [comment]
Yup, error handling in general violates DRF practices - errors should either be returned as field errors under the fields name, with general errors under `non_field_errors` key, but theres a lot of custom stuff in code that overrides this.

**Comment by maciej-jaworski** [comment]
I streamlined how API errors work, added some basic docs here: 
https://unicef.gitbook.io/prp/technical-documentation/api-documentation/error-handling

> backend seems to always return one error at a time (first found I guess) instead of a whole list
Fixed it in once place, could still use more improvement but required more in depth review of which errors could be validated simultaneously.

**Comment by sethgold8** [comment]
Everything working well, except when I go back after an error to edit the 'baseline' the Line where the # is supposed to be on is not there. Also sometimes it does not appear for target

![Screen Shot 2018-03-16 at 10.05.09 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206455f56b7191a379ef0c2b54415f47bc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e04c5ca01a3f65e57e3f6e0a.png)

**Comment by sethgold8** [comment]
tested a few times again and not seeing the issue so pushing forward -Seth
