### ISSUE TITLE
IP bugs from Rob Call IP/PMP Sync

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#518]
- Everything is good but waiting on Shared Partner - Seth and @n1207n 

```
{
id: 100,
vendor_number: "2300067192",
deleted_flag: true,
blocked: true,
name: "STEP",
short_name: "",
partner_type: "Civil Society Organization",
cso_type: "International",
rating: null,
shared_partner: "No",
shared_with: null,
email: "ANNET@STEP-IRAQ.ORG",
phone_number: "533210363",
total_ct_cp: "0.00",
total_ct_cy: "0.00",
hidden: true
},
```

- [x] For submitted report, total cumulative progress report does not update. Same with cluster

![Screen Shot 2018-02-28 at 3.51.27 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77216456fb6b7191a37bf1172a4f5d585ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df742e94b57a1133564e0702431.png)

- [x]  Indicator title search should ignore capitalization. Apply that to all search filters

@n1207n  

- [x]  We need from Rob: Reporting periods, workspace, amendments, pd api, partners api (Go over with Sillin)

- [x] remove reports from IP reporting indicators list

![Screen Shot 2018-03-01 at 11.39.55 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454f26b7191a379ee0c2858415a4bbc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29b4bc259f34ae84456a7113563e4723f6e0a.png)

- [x] on progress report add: submitted by: XYZ etc. (if set then) on behalf of: YZX, submission date: XYZ (3 separate lines if we have to keep it clean).

- [x] Make report details for submitted reports in a consistent location

@marcindo 

![Screen Shot 2018-03-01 at 3.49.39 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454f26b7191a37bf116224f5c565ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a29941c95df742e8495da01b3163ee722431.png)

- [x] Disable colors for links you've already clicked @marcindo 

![Screen Shot 2018-03-06 at 4.22.54 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454f56b7191a37cf110294f5a5b5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df44be24a54a0113f67e5742431.png)

- [x] UX improvement. Once data is successfully entered on disaggregations table, please update achievement in reporting period field.  @n1207n 

![Screen Shot 2018-03-08 at 10.23.55 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77206454fb6b7191a379ef0c2952415a4bbc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e14857a61b3165e6733e6e0a.png)

**Comment by marcindo** [comment]
@sethgold8 I see free text searches already ignore capitalization on the backend so there's little point doing that on frontend, if this is not working somewhere, then again, better to fix on the backend

**Comment by n1207n** [comment]
@sethgold8,

Item #1 needs frontend, backend, and PMP data API to change. I can try to close the gaps in PRP frontend and backend sides.

@robertavram, `https://etools-demo.unicef.org/api/v2/partners/` endpoint is lacking `alternative_title` and `shared_partner` for Partner serializer, is it possible to introduce them in v2 Partner list API? For At the moment `shared_partner` in PRP Partner model is defaulted to "No" since PMP data sync didn't provide it, is this field still relevant or deprecated?

**Comment by n1207n** [comment]
Pushed some commits to develop branch in order to enforce correct field name to render in Polymer and PMPPartnerSerializer. At least, address and basis_for_risk_rating are correctly displayed if value exists.

I have a concern that PMP sync partner API data may have some quality issue... I don't see basis_for_risk_rating value from API but yet the UI screenshot that Kunal sent us has value. PMP data sync serializer in PRP maps to each valid field currently.

As a duck tape, we can set values in Django admin for demo purposes if some of the values didn't get synced over from API.

**Comment by sethgold8** [comment]
#works good :)

moved " Make all fields in partner sync work properly. ...partner type date last accessed, address, phone , number, email are not appropriately synced." to #539
