### ISSUE TITLE
Adding an existing project from OCHA

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#563]
- [ ] Select from OCHA
https://projects.invisionapp.com/d/main#/console/13398823/279786967/preview

https://projects.invisionapp.com/d/main#/console/13398823/279786968/preview

**note** Make sure IMO being able to add a project on behalf of a partner (partner dropdown). Eg. route where we do that: /app/GA/cluster-reporting/plan/246/response-parameters/partners/projects

**Comment by chachra** [comment]
@momimomo Might need to branch off branch #540-partner-project-import CC @maciej-jaworski

**Comment by momimomo** [comment]
@chachra: should IMO be able to assign a partner to project imported from OCHA, or should it be decided by API based on partners assigned to project in OCHA?

**Comment by chachra** [comment]
@momimomo good question. Does that project in OCHA come with a partner field @maciej-jaworski ? Does it always have it?

If yes, then its a bit tricky for us since well we might not have that partner in our db associated with this cluster / response etc. no?

If we import it for the partner that the IMO is selecting and its not the partner set in OCHA, then technically we're doing wrong.... so maybe IMO should never be selecting a partner when "OCHA" option is selected.

Other issue is we allow partner to import from OCHA as well!? Do we should them only their OCHA projects then?

If yes..... then maybe we have a solution for both situations (somehow). Meaning the projects dropdown for import will only show the logged in partner or selected partners projects. Does OCHA support partner name filtering or some kind of key for a partner?

**Comment by maciej-jaworski** [comment]
It has it most of the time, I did the partner import but I don't know if thats the correct way to go about this since theres no way to tie the partner to existing users afaik and matching by name sounds awful for all the usual reasons.

**Comment by momimomo** [comment]
endpoint and edit mode fixes for 563 and 536 are on this branch: `563-assigning-partner-to-ocha-project`, so it should be applied after 536 merge.

**Comment by momimomo** [comment]
limited visibility of OCHA import option when adding a project for partners under response plan without permissions for pulling from OCHA.

**Comment by momimomo** [comment]
Also, merged with 536, so it's already on staging.

**Comment by sethgold8** [comment]
Am concerned that it is only working for Pakistan @momimomo  . Let's go over this on our standup on Wednesday in case it's a matter of OCHA not having the data or something I may be missing

![Screen Shot 2018-04-17 at 1.37.56 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f46b7191a379f1112c4f5a595ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df448e84452a1113f65e7762431.png)

- [ ] Cannot add a Partner to this project in `Pakistan Transition Plan: Humanitarian Component 2018` as IMO. Cannot save the project because no partner can be added

![Screen Shot 2018-04-17 at 1.40.15 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f46b7191a379f1162b4f5e5a5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df448e84452a3123664e1772431.png)

![Screen Shot 2018-04-17 at 1.40.32 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276455f46b7191a379f1162b4f5c5d5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df448e84452a3103567e5702431.png)

cc @chachra
