### ISSUE TITLE
Use Proper DJango Admin form for user password

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#623]

**Comment by maciej-jaworski** [comment]
Changes delivered on develop, [single commit](https://github.com/unicef/etools-partner-reporting-portal/commit/9b36fdcaecb05cb266f20f1eacc49f2bc9b20462)

**Comment by sethgold8** [comment]
- [ ]  Getting error when try to save new user with pw added. Also this may have caused all of changing ' User Info" to break when saving as mentioned in #628. Plz test more before pushing as this also caused the demo to not go as planned.

![Screen Shot 2018-04-26 at 11.13.47 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f56b7191a379ee0c2a52415b49bc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb2984cc259f349e54a53a2163164e173306e0a.png)

**Comment by n1207n** [comment]
I think the fix may be already implemented now. In addition, I modified AD integration to set username with email address and unusable password for satisfying Django's requirement on User, so that IMO user only needs to activate the user without having to change username/password in Django admin.

Will test this in staging soon as it is getting deployed.
