### ISSUE TITLE
Need Splash screen for AD when user logs in from Unicef Email

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#671]
We do not have the splash screen when a user comes from their Unicef Email

it should be the same and say "Account created. Please wait 1-2 business days for your admin to approve you. If it has been longer then 1-2 business days, please email X to get you approved. "

When a user signs up from AD, the backend may add `UNICEF User` group to the created user object, so the user will always have a group.

Change the frontend logic to check the followings:
* groups field is empty
* OR groups field only has `UNICEF User` record.

If any of these is true, then show the placeholder UI.

------ User profile API response example
![Screen Shot 2018-05-16 at 2.52.00 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58d2f674dc6eec1a00ff72e7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266455f56b7191a37af117294f5f5f5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df44de44d52a1163060e17f2431.png)

**Comment by momimomo** [comment]
so it also could have field `is_unicef_user` or something like that, right, but on the above example, the logic based on such response from API would just make it so that we show it to all types of users (imo, ao, pe, pv) with no permissions, right? 

So, we want to basically just set the imo/ao/pe/pv settings for AD users automatically after registering, and it's not going to be empty groups? I don't understand how it should be encompassing empty and not at the same time.

The splash screen was delivered week or two ago for empty groups. Was it working? I have no way to test AD login, so let me know how to do that. Also for Unicef user if it's possible. Then I could see the response from API.

**Comment by sethgold8** [comment]
@momimomo amd getting a 502 error when testing with a fake email. Have not sent to unicef to test yet.
![Screen Shot 2018-05-24 at 1.13.16 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77266456f76b7191a379f113284f5e595ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df44ce04457ac173f62ef742431.png)

**Comment by sethgold8** [comment]
@momimomo can you make the splash screen text a bit bigger. Right now its super small and hard to read

**Comment by momimomo** [comment]
Increased font sizes to 28 / 16 px.

**Comment by sethgold8** [comment]
pushing through
