### ISSUE TITLE
Reporting Requirements are not showing on PD

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#733]
- [ ] We are missing Reporting Requirements from PD

![Screen Shot 2018-06-19 at 2.26.47 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256455fa6b7191a37af1102d4f5b585ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df442e54956ac113561e0752431.png)

We should include them as  Programme Documents Tab on the bottom show requirements.  https://unicef.gitbook.io/prp/product-end-user-documentation/ip-reporting/user-interface

Here is an example image of how it should look

![Screen Shot 2018-06-19 at 2.30.59 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256455fa6b7191a37af1112b4f5a565ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df442e54956ad11366ae2702431.png)

#frontend

**Comment by n1207n** [comment]
Turns out ProgrammeDocumentSerializer already includes `reporting_periods` field, but had to add `report_type` for each `reporting_periods` item.

@rkrupinski,

**Technical notes for frontend**
There is a field called `reporting_periods` at ProgrammeDocument API data to implement above UI image.

Before iterating, create 3 sub lists from `reporting_periods` field by report_type (QPR, HR, and SR).

Sort each sub list by start_date. Iterate QPR list first, HR list, then SR list to populate UI.

**Comment by sethgold8** [comment]
working good :)
