### ISSUE TITLE
When trying to upload an attachment in SR, replace 'Change' word with 'Upload'

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#742]
![Screen Shot 2018-06-21 at 5.34.34 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256456f26b7191a37df1112f4f5c5b5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df442e74f52a3103265e0742431.png)

**Comment by rkrupinski** [comment]
1. The text is a part of an [external component](https://github.com/unicef-polymer/etools-file)
2. Normally it reads "Upload" and only shows "Change / Delete" buttons once there's an actual attachment. On the screenshot a data issue demonstrates itself where we actually have an attachment, but it's "empty":

```json
[{ "path": null, "size": null, "file_name": null }]
```

cc @n1207n

**Comment by n1207n** [comment]
@rkrupinski,

The API response should be actually just `{ "path": null, "size": null, "file_name": null }`, without the list, because there can be only one attachment for ProgressReport.

Also, the `{ "path": null, "size": null, "file_name": null }` response tells you that we have an empty attachment, not as the empty object response.

I'll update the API response without a list, and polymer should look up `path` in the response object to determine there is no attachment or not. If `path` is null, then the component should say `Upload` otherwise `Change or Delete`

**Comment by n1207n** [comment]
I've updated the API serializer, so it should no longer be list format.

**Comment by rkrupinski** [comment]
@n1207n There's one more place you need to update:

Uploading an attachment (`PUT`) returns a collection.

**Comment by sethgold8** [comment]
Am still seeing 'Change' cc @rkrupinski @n1207n

![Screen Shot 2018-06-27 at 2.00.56 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256456f46b7191a37af1122b4f5a595ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df54be04e56a7123e60e2752431.png)

**Comment by rkrupinski** [comment]
You will keep seeing "change" when there's an actual attachment. "Upload" alone only appears when the component renders "empty" or upon clicking "delete". We can fork / submit a pull request to [etools-file](https://github.com/unicef-polymer/etools-file) to change that but I'd rather advise against it since this behaviour is pretty consistent.

**Comment by sethgold8** [comment]
thanks @rkrupinski all good and closing this ticket
