### ISSUE TITLE
Default value must not be 0 and must be changed to blank in the enter data form.

### ISSUE THREAD

**Issue by sethgold8** [unicef/etools-partner-reporting-portal#749]
For both, IP/Cluster when entering disaggregation date, can we set the default to blank as opposed to 0

![Screen Shot 2018-06-25 at 5.02.52 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77256456f66b7191a37df112294f5a5d5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df442e84a54a0153066e4742431.png)

**Comment by rkrupinski** [comment]
So it turns out that there already is a logic in place to default empty values to `"-"`. We can't default zeros to `"-"` since zero is a perfectly valid value. The "empty" reports being generated on staging all have totals explicitly set to `0` which effectively prevents `"-"` from being displayed:

![totals](https://user-images.githubusercontent.com/775177/41895979-b86d76b4-7923-11e8-9efa-822046ee6f53.jpg)

The only sane solution I can think of right now is removing those.

cc @n1207n

**Comment by n1207n** [comment]
Errr I personally don't want to poke total of totals value to be null, given the value is relied on many backend logic.

Could we introduce a hardcoded condition where if the key is "()" and `c` value is zero then show empty placeholder instead?

cc @rkrupinski

**Comment by sethgold8** [comment]
Spoke with @KKaselkar and we decided not to do this today as it does not add enough value. Closing ticket
