### ISSUE TITLE
List of constrained indicators

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#796]
1. Log into Cluster-PRP as IMO
2. Select Workspace = "Somalia".
3. Select Response Plan = "Water Sanitation in Somalia 2018 (FA)"
4. Go to Dashboard. Keep Cluster set to "All".
5. Click on an Indicator under "List of constrained indicators"

It will take you to the Reporting Results section and SUBMITTED REPORTS tab, but the Indicator is not displayed.

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/42837493-3e61b0e2-89cc-11e8-86a7-c1c46ba2ce9f.png)


![image](https://user-images.githubusercontent.com/32198614/42837497-41db0cfa-89cc-11e8-831f-dab1e0602675.png)

**Comment by sethgold8** [comment]
- [ ] Can confirm we are not displaying 'Constrained indicators' in the dashboard

**Comment by n1207n** [comment]
Update here. I was able to replicate this on dev environment. I created a Cluster objective indicator, generated its reports, and submitted one of reports with constrained status.

The issue is coming from the fact that `List of constrained indicators` only looks at Partner activity indicators. Therefore, the list of constrained indicators does not show this.

My understanding is that any indicator information shown in cluster dashboard revolve around partner activity only.

With above insights, I consider this is not a bug issue.

**Comment by KKaselkar** [comment]
I agree it should be at partner activity level but shouldnt it display the indicator itself on the reporting results section.

**Comment by sethgold8** [comment]
There is no 'constrained Filter' so it will show a list for Partner Activity Indicators
![Screen Shot 2018-11-13 at 4.53.14 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226455f06b7191a37cf117284f5e5b5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df249e04853ac113063e37f2431.png)

**Comment by KKaselkar** [comment]
ticket 1047 added for this issue
