### ISSUE TITLE
List of overdue indicators

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#797]
1. Log into Cluster-PRP as IMO
2. Select Workspace = "Somalia".
3. Select Response Plan = "Water Sanitation in Somalia 2018 (FA)"
4. Go to Dashboard. Keep Cluster set to "All".

The Reports listed under "List of overdue indicator reports" were NOT created under the specified Response Plan in Workspace Somalia. Looks like these were created in Workspace Iraq.

User has access to both Somalia and Iraq workspace but shouldnt it only show Iraq indicators when Iraq is selected in the workspace drop down list

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/42837665-b43b47d8-89cc-11e8-9b0a-b9effebfea8c.png)

**Comment by sethgold8** [comment]
@KKaselkar this is a issue from testing and would not happen in real life.

A tester marked Agency for Tech Dev (Iraqi partner) in Somalia  clusters through Django Admin. This UI shows indicator reports from all the partners, from all clusters in this response plan. Since this partner belonged to Somalia cluster, therefore UI showed indicator reports from Iraqi partner. 

![Screen Shot 2018-07-18 at 4.05.53 PM.png](https://waffleio-direct-uploads-
production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246455fb6b7191a37cf1122e4f5a5c5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19041c95df54ae84850a6163e63e4712431.png)

Here's a screenshot after we cleaned up the partner. WIll close this ticket soon.

![Screen Shot 2018-07-18 at 4.08.32 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77246455fb6b7191a37cf112234f5c5d5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a29941c95df54ae84850a1103466e0722431.png)
