### ISSUE TITLE
Ratio and percentage - data entry table error

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#871]
PD number: IRQ/PCA2018245/PD2018441
dev.prp environment 
Iraq workspace
demo pmp environment

In case of ratio and percentage the data entry table doesn’t display the layout / format of the table correctly. It should be similar to the data entry table as implemented in cluster for ratio and percentage.

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/44602777-91f99080-a7ae-11e8-88b5-612c2228aa96.png)

**Comment by chachra** [comment]
@KKaselkar this indicator was setup as a percent? @robertavram in current api there is no way to know other than d=100 in the key. Can you expose blueprint as well please? safer that way.

**Comment by chachra** [comment]
@robertavram some quick help on this will be great so we can resolve this one. Tx.

**Comment by robertavram** [comment]
will you want the entire blueprint exposed or just flat serialize the `unit` and `display_type` in the same structure

**Comment by robertavram** [comment]
keys available in etools-demo.

**Comment by n1207n** [comment]
Confirmed that API fields are added from etools-demo. Will make changes to task. Thanks.

**Comment by n1207n** [comment]
@robertavram,

I see some indicators from PD sync have no value in `unit` and `display_type` fields. What I'm going to do is to look up their baseline dictionary, and set `unit` and `display_type` to Quantity type if denominator is 1, otherwise will be set as percentage.

![Screen Shot 2018-08-29 at 1.27.21 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58d2f674dc6eec1a00ff72e7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6456fa6b7191a379f1102c4f5d5e5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19f41c95df54ee44a51a0153167ee752431.png)
![Screen Shot 2018-08-29 at 1.27.25 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58d2f674dc6eec1a00ff72e7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772b6456fa6b7191a379f1102c4f5d5a5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19f41c95df54ee44a51a0153167e47f2431.png)

**Comment by KKaselkar** [comment]
Resolved:
![image](https://user-images.githubusercontent.com/32198614/46627986-39861480-cb0a-11e8-8fea-915d9741e0a7.png)

![image](https://user-images.githubusercontent.com/32198614/46628009-4acf2100-cb0a-11e8-9317-1cb94dbff403.png)
