### ISSUE TITLE
Be able to export a CSV/xls with data for multiple indicator reports in it

### ISSUE THREAD

**Issue by chachra** [unicef/etools-partner-reporting-portal#88]
Depends on format in #87.

After importing data into a progress report or indicators in cluster reporting user can make more changes before submitting.

Any filtering done in https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/243476913 should reflect on exporting queryset.

Any imported indicator location data belonging to submitted or accepted IR will be ignored.

** Import validation: if partner is importing, only import reports where Partner ID == user{Partner id}

**Comment by kasfaw** [comment]
finalizing specifications here: https://docs.google.com/spreadsheets/d/1JhM7yqcSJtRE6iGJGSuObEOadhk6Y0r6RRQupee4mXQ/edit#gid=0

**Comment by kasfaw** [comment]
@chachra @n1207n Done with specification. Will send to UNICEF shortly. Major open question is how we help (for analysis) associate parent-child locations. What do you guys think of having a uniform lookup tab at the end? I put an example in last tab.

**Comment by kasfaw** [comment]
@chachra do we plan to provide a an XML view of this API  too? Jean said running a powerquery formula from an XML file is very powerful for analysis.

**Comment by n1207n** [comment]
Created a branch and will add xlsx python parser library to prepare the implementation.

**Comment by kasfaw** [comment]
@dfryta please review the export/import specification here (ignore the 3rd tab): https://docs.google.com/spreadsheets/d/1JhM7yqcSJtRE6iGJGSuObEOadhk6Y0r6RRQupee4mXQ/edit#gid=0

a few guiding points:
- same format is to be used for exporting and importing new reports in cluster reporting
- exports are based on filtered values. example: https://projects.invisionapp.com/share/EDBIM0Y8M#/screens/243476913
- this is an example of indicators with 3 levels of disaggregation (gender, age, disability) but there could be indicator 1, 2 or no disaggregations fyi
- the red row indicates what model each information is coming from along with the field name
- the comment tab explains various behaviours of columns, etc... especially how import logic should work

**Comment by dfryta** [comment]
Thanks @kasfaw.

Let me check this out and I will back to you with list of questions. At this moment please let me know what difference between row 3 (example: #sector+cluster) and row 9 (red one). From you information red one holds  field name description. So what is row 3?

And is it possible to get template excel file as it should looks like after export with some fake data? (other words exactly how it should looks like, removing all additional information).

Thanks!

**Comment by kasfaw** [comment]
@dfryta row 3 is static similar to row 1. row 9 is a reference I created for you so you can trace each column back to specific models (row 9 is not meant to be in the export).

Rows 4-6 are fake data but will add more tomorrow for variety.

**Comment by kasfaw** [comment]
@dfryta row 3 is static (similar to row 1). Row 9 is a reference I created so you can trace each column to its respective data model (row 9 should not be included in exports). 

Row 4-6 are fake data but will add more tomorrow for variety.

**Comment by dfryta** [comment]
@kasfaw note to our meeting today. There are plenty questions and issue that we need resolve before moving forward:

- Disaggregation should have limited choices, name -> type, currently: gender, height, age
- Column O - location.gateway.name - there is no gateway field 
- S-U Each sheet should represent all indicator reports that share a common set of disaggregation IDs - look at point 1 - each of indicators have own disaggregations! Currently each of indicator will have own spreadsheet?
- S-BE These columns are dynamically generated according to the disaggregation values available for each indicator - cannot be done (easily). Since we have to import back, fields list needs to be fixed. Otherwise we won’t be able to recognize field to import. I am also not sure what are those ID numbers in column names that are static(!!!). 
- Columns BF - BV should be moved before dynamic disaggregation data. Otherwise is impossible to parse import back, since column position might be different per each indicator (different disaggregation types).
