### ISSUE TITLE
Dual Reporting IP & Cluster Due dates dont match

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#892]
Dev.prp environment 
Iraq workspace
Chrome browser

•	For IP PRP – end date for humanitarian reports is the same as the due date selected in PMP by UNICEF.
•	For Cluster PRP – due date for humanitarian reports is a day after the end date of the report.
This difference in due dates affects dual reporting , see the below results in IP PRP:
•	HR1 – has only UNICEF HR
•	HR2 – has both cluster and IP HR
•	HR3 – has only Cluster HR

because of the different due dates they dont club in one HR report

**Comment by KKaselkar** [comment]
PMP screenshot
![image](https://user-images.githubusercontent.com/32198614/45378742-4b889c00-b5cc-11e8-97c2-fe46881f740e.png)

IP PRP screenshot PCA 2016/04/SHPD2018504
![image](https://user-images.githubusercontent.com/32198614/45378799-6c50f180-b5cc-11e8-8e73-c484087f0a4d.png)

**Comment by sethgold8** [comment]
@KKaselkar PMP due date must match with Cluster. Otherwise cannot get dual reporting consistently.

![Screen Shot 2018-09-11 at 5.41.56 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b772a6455f26b7191a37df1162a4f5a595ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a29941c95df54de64c57ad103267e17e2431.png)

**Comment by KKaselkar** [comment]
@sethgold8  the highlighted text in your email is for cluster, but for IP PRP their requirements were to have the due date same as end date, Anyways both IP and Cluster as of now have different due dates calculated in the system and I am trying to understand which one is correct.

**Comment by KKaselkar** [comment]
Aligning IP PRP due dates  in PMP to cluster due dates so closing this card as it needs work on PMP.
