### ISSUE TITLE
Dual reporting - Unicef tab appears twice

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#895]
Dev.prp environment
Iraq workspace
Chrome browser

2 Cluster indicators are add in PMP to a SSFA with one UNICEF high frequency indicator

Locations in both UNICEF and cluster dont match but the reporting dates match.

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/45380425-a7edba80-b5d0-11e8-9968-d85fe2db18b3.png)


PMP:
![image](https://user-images.githubusercontent.com/32198614/45380443-b50aa980-b5d0-11e8-8bf1-96fc9620a8c1.png)

**Comment by sethgold8** [comment]
@KKaselkar what PD #? Screenshot is a bit blurry

**Comment by KKaselkar** [comment]
Number of SSFA:  IRQ/SSFA2018265

**Comment by n1207n** [comment]
I found a problem which is a data issue. The PD output from this SSFA has 2 LLO indicators pointing same cluster indicator. From the screenshot, I see 2 `MB_ClustAct_4_indi_2_11 Sept`. You can only add this cluster indicator once and PMP should throw validation on this.

We can only allow 1 ClusterActivity indicator to connect with LLO indicator, due to dual reporting requirements. This causes cluster reporting to essentially create 2 copies of partner activity indicator references to cluster activity for that partner, which is illegal in PRP. UNICEF dual reporting tab appearing twice is an evidence of that.

Since PMP does not have a validation on re-using same cluster indicator to create, the report generator logic behaves incorrectly.

I advise to edit this PD in PMP not to re-use same cluster activity indicator in PD output. Whenever this is edited, we'll need to delete corrupted progress reports and re-run PD sync and report generation.

**Comment by KKaselkar** [comment]
Resolved. double tab doesnt appear if the cluster indicator is used for a PD for a Partner
