### ISSUE TITLE
Redundant re-fetching of PSs?

### ISSUE THREAD

**Issue by rkrupinski** [unicef/etools-partner-reporting-portal#90]
When a pd is selected (from a list), pds seem to be re-fetched:

https://drive.google.com/file/d/0BxDYQDDFAykYUzlYQkhCcERudk0/view?usp=sharing

**Comment by adamtlord** [comment]
@rkrupinski  This is a tricky one, I'm not sure how to solve it. I noticed the re-fetch only happens the first time a user clicks on a pd. 

I _think_ the list of pds is reloading because it's dispatched in  `_handleInputChange()`, which is triggered by changes to **programmeDocumentsUrl** or **queryParams**. 

If the user navigates to app/<location>/ip-reporting/pd, `etools-data-table-footer` calls `_computeParamValue()` with its default **page=1** and **page_size=10**, and these params get added to the url. 

When the user clicks on a pd and goes to the pd-details view, these params are removed from the url, triggering pd-index's `_handleInputChange()` again, and dispatching the fetch again.

If the user then goes back to the list of pds, the page and page_size params are not re-added to the url (not sure why) so from then on the queryParams don't change if the user goes back to a pd-details view, and the fetch doesn't happen again.
