### ISSUE TITLE
Incorrect calculation in QPR1

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#946]
dev.prp environment 
Iraq workspace
https://dev.partnerreportingportal.org/app/IRQ/ip-reporting/pd/950/report/237/view?page=1

Submitted one HR report for PD PCA 2016/09/PD2018457

after that submitted first QPR report in the same PD PCA 2016/09/PD2018457

In this scenario as the QPR is the first QPR report the total cumulative progress and achievement in reporting period values must be the same as there was no other QPR submitted before this QPR report.

**Comment by KKaselkar** [comment]
![image](https://user-images.githubusercontent.com/32198614/46425044-c72bc380-c708-11e8-8491-fefb48441845.png)

![image](https://user-images.githubusercontent.com/32198614/46425077-d90d6680-c708-11e8-911f-60daaf616e2d.png)


![image](https://user-images.githubusercontent.com/32198614/46425128-f3474480-c708-11e8-893e-cd8b2788fc45.png)

**Comment by sethgold8** [comment]
@kkaselkar  I just submitted QPR IRQ/PCA2018259/PD2018451-1 this and I think it works fine.

As you can see below, there was 0% in total cumulative progress as this was the first QPR submitted. Can you retest with a different QPR as I think there was a fake data issue. 

![Screen Shot 2018-10-03 at 1.41.19 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236454f06b7191a379f1162a4f5e565ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df543e4445ca7163e66e2722431.png)

**Comment by n1207n** [comment]
Hi Kunal,

Seth and I replicated your report data entering and submission steps to understand the issue here.

We entered data for HR1 report in your PD and submitted the report. Since this is HR report, the report got automatically accepted. When any progress report is accepted or is sent back, PRP system calculates the indicator total which is `Total cumulative progress` for an indicator in the progress report. The below screenshot shows each PD indicator's indicator total and HR1 indicator report total.

![Screen Shot 2018-10-05 at 4.53.34 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58d2f674dc6eec1a00ff72e7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236454f66b7191a37cf117284f5c5b5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a29841c95df543e64551a0173566e5722431.png)

The next screenshot is when we finished entering data for QPR1 but have not submitted yet. You'll see that `Total cumulative progress` is same as the one from HR1 report, since that was the last solid indicator total value upon accepting HR1 report for each indicator. Obviously, `Achievement in the reporting period` is different because we entered new data for QPR1, and this is the indicator total for QPR1 progress report's perspective.

![Screen Shot 2018-10-05 at 4.55.25 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58d2f674dc6eec1a00ff72e7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236454f66b7191a37cf1172e4f5d5a5ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a29841c95df543e64551a0173566e47e2431.png)

Lastly, the final screenshot is when we accepted QPR1 progress report for this PD. You'll see that `Total cumulative progress` has been updated since new progress report (QPR1 in this case) has been accepted in our system. Therefore, PRP system recalculates each indicator's total from 2 progress reports now (HR1 and QPR1)

![Screen Shot 2018-10-05 at 5.00.17 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58d2f674dc6eec1a00ff72e7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236454f66b7191a37df1122b4f5e585ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19141c95df543e64551a0173566ee772431.png)

According to our signed-off specs, we don't calculate `Total cumulative progress` separately for HR and QPR. They are pooled together when it comes to recalculation.

It seemed that your expectation is to only  calculate `Total cumulative progress` for QPR report only, in case an officer decided to enter QPR report manually instead of pulling data from HR.  I can see an edge case where `Total cumulative progress` for PD indicator can be bloated after accepting HR1 and QPR1, if QPR1 total is drastically different than HR1 total. At that point, what's the point of submitting HR reports if we only calculate `Total cumulative progress` for QPR only?

This needs some thinking around.
