### ISSUE TITLE
Enter data button and upload attachment options missing for sent back report

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#947]
dev.prp
Iraq workspace

PCA 2016/09/PD2018457

- [ ] Enter data button and upload attachment options are missing for QPR which is sent back from PMP

- [ ] Also check same thing with SR.

**Comment by KKaselkar** [comment]
PMP:
![image](https://user-images.githubusercontent.com/32198614/46425422-a879fc80-c709-11e8-8261-3f8355288e52.png)

PRP:
![image](https://user-images.githubusercontent.com/32198614/46425453-bb8ccc80-c709-11e8-9696-5270330b5356.png)

![image](https://user-images.githubusercontent.com/32198614/46425544-ec6d0180-c709-11e8-8814-7d26ca3e88b2.png)

![image](https://user-images.githubusercontent.com/32198614/46425568-03abef00-c70a-11e8-97c1-87f88891c834.png)

**Comment by sethgold8** [comment]
blocked by #948

**Comment by n1207n** [comment]
I believe frontend code is now showing input fields and enter data button if the progress report is sent back status.

We should allow to enter data and update other info sections even if the progress report status is sent back. Obviously if it's submitted status, then it should not show input fields and enter data buttons.

**Comment by sethgold8** [comment]
@KKaselkar 

There was a duplicate ticket opened that you opened #967, that I closed since it was the same as this. 

Anways, this is working for me so moving it to UNICEF QA. PLease share details where it does not work or move to accepted if you cannot reproduce
Partner: The Human Right Center in Iraq
IRQ/PCA2018259/PD2018442-1 for SR1
IRQ/PCA2018259/PD2018448-1 for QPR 2

![Screen Shot 2018-10-10 at 11.54.44 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f36b7191a379ee0c2e55415b4abc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29843c259f348e84c5ca31b3361e676316e0a.png)

![Screen Shot 2018-10-10 at 11.55.22 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f36b7191a379ee0c2e54415d4cbc30254d58eeb9cb74fce36f34985619e8d93e097cc56811afbe8b4cbe04ba20824d80b1ba8d4ec6fa2137a5dad11b61435c52dcbd4f3fb29843c259f348e84c5ca31b3063e070326e0a.png)

**Comment by KKaselkar** [comment]
Resolved , the enter data button and upload option appears now
