### ISSUE TITLE
Add project from OCHA button is disabled

### ISSUE THREAD

**Issue by KKaselkar** [unicef/etools-partner-reporting-portal#987]
Browser:Chrome 
Workspace:Iraq 
Steps: 
-Login as a cluster member. 
-Select a reponse plan which is from OCHA. 
-Go to My Planned Actions---> Projects 
-Click on "Add Project" 
-Select "From OCHA" 
Result: "From OCHA" radio button is disabled.

Current View

![Screen Shot 2018-10-16 at 1.42.46 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f56b7191a379f116294f5b595ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a19e41c95df542e64f57a2113060e27f2431.png)

How it should look
![Screen Shot 2018-10-16 at 1.45.17 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59f1189df815e200161f654a/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f56b7191a379f1162e4f5e585ecc3c4a4356bcbbd671f3e57862804e0ee5823b5777933d12aab1d11eba01ba29894a82b0bb884ad2f42f67b6d5db1063474f4dcbed5727a29841c95df542e64f57a311326be3702431.png)

Specifications link: https://unicef.gitbook.io/prp/product-end-user-documentation/cluster-reporting/response-parameters-setup#adding-a-project-for-a-partner-as-an-imo

**Comment by sethgold8** [comment]
Also just to note, i have tested this with Partner: Afkar Society for Development and Humanitarian Relief

OCHA External ID: 4470

**Comment by n1207n** [comment]
I believe the `From OCHA` radiobox shows up under 2 conditions:
- The response plan must be imported from OCHA
- Partner needs to have OCHA external ID

**Comment by n1207n** [comment]
@groinder, when I choose From OCHA radiobox, it does not display dropbox UI for OCHA project dropdown. It's as if mode is not `ocha` after choosing radiobox sadly.

**Comment by groinder** [comment]
1. Visibility of this radiobox depends on `can_import_ocha_projects` flag from  `/api/core/workspace/<id>/response-plan/` endpoint.

2. Disabled state on this radiobox occurs when partner doesn't have `ocha_external_id`.

3. @n1207n Radiobox didn't work and the issue wasn't related to any recent changes as it was broken for a long time due to wrong Polymer syntax - missing quotation marks. Of course the Polymer didn't show any errors/warnings whatsoever it just simply didn't work... I fixed it now, and fixed the syntax in all other places as well.
